a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfabetico? ', a.isalpha())
print('É um digito?', a.isdigit())
print('É printável?', a.isprintable())
print('Está capitalizada?', a.istitle())
print('Está TODA em maiusculas?', a.isupper())
print('Está TODA em minúsculas? ',a.islower())